create table Professor(
	id			int not null primary key
				generated by default as identity (start with 1, increment by 1),
	name		varchar(200) not null,
	email		varchar(200) not null unique,
);

create table Course(
	id			int not null primary key
				generated by default as identity (start with 1, increment by 1),
	title		varchar(200) not null,
	available		boolean not null,
	level		varchar(20),
	time		int,
	professor_id int references Professor(id),
);
